name: xnat-ais
channels:
- conda-forge
- defaults
dependencies:
- python
- jupyterlab
- mne
- mne-bids
- mne-connectivity
- pip

- pip:
  - fileformats
  - fileformats-medimage
  - arcana
  - arcana-xnat